### ISSUE TITLE
일부 상점 스킨배너가 표시되지 않는 오류

### ISSUE THREAD

**Issue by weqjojio** [WolfgangKurz/LastOriginWiki#102]
일부 스킨의 상점배너가 정상적으로 표시되지 않고 있습니다.

페로 - 카페 아모르  구글판
탈론페더 -  웨딩 구글판
스트라토 앤젤 - 바니 구글판
로열 아스널 - 카페 아모르 구글판
니바 - 역바니 스킨 구글판
엔젤 - 데이트 스킨 구글판
장화 - 카페 호라이즌 구글판
천아 - 카페 호라이즌 구글판
장화, 천아 - 갸루스킨 배너 원스, 구글판
아우로라 - 카페 호라이즌 구글판
아자즈 - 카페 아모르 구글판
마키나 - 웨딩 스킨 구글판

제가 확인한 배너 미표시 스킨의 목록입니다. 해당 배너들은 엑박으로 표시되고 있습니다. 

이 외에도 하이에나, 워울프의 교복 스킨과 멀린의 음악회를 열다 스킨의 배너가 등록되어 있지 않습니다.

**Comment by WolfgangKurz** [comment]
일부 예전 스킨의 배너 이미지는 당시 보존해두지 않아 없는 상태입니다.

**Comment by weqjojio** [comment]
그렇군요... 아쉽지만 그래도 계속 교본 운영해주셔서 감사합니다
