### ISSUE TITLE
Help, Why is every live2d is like this??

### ISSUE THREAD

**Issue by Weeawuu** [WolfgangKurz/LastOriginWiki#111]
I'm playing on my phone and people tell me I need to delete a file in Andriod>data>lastorigin>unity but I can't even delete it and even on my laptop help me pls

My phone is ver 13 btw and Itel A70
![image_2024-08-10_005443490](https://github.com/user-attachments/assets/8dc8dfcd-7f6d-42ba-bd59-c42a4fee45ce)

**Comment by Weeawuu** [comment]
delete a folder files to fix but I can't because google said so WTF

**Comment by WolfgangKurz** [comment]
This repository is for `Tactics Manual`, not `LastOrigin` game.

You should report to Game service provider, or ask to other communities.
