### ISSUE TITLE
Wrong drop in 다시 시작하는 바다 모험

### ISSUE THREAD

**Issue by NexySlime** [WolfgangKurz/LastOriginWiki#113]
![Screenshot 2024-09-05 224829](https://github.com/user-attachments/assets/6bdddb0d-f1fd-40ad-8119-d688e6091770)
![Screenshot_20240905-224821](https://github.com/user-attachments/assets/7d21606f-e487-4960-8f53-bea7fab8dfd4)

Drops in every stage of the event have extra?

**Comment by WolfgangKurz** [comment]
There's two data about map drop.

One is `Preview table`, and other one is `Real drop table`.

Seems devs didn't set `Preview Table` well.

Tactics Manual using `Real drop table` data.
