### ISSUE TITLE
Bug in poi's lobby animation

### ISSUE THREAD

**Issue by dmsdms5090** [WolfgangKurz/LastOriginWiki#117]
![Screenshot_20240916-205229_Brave](https://github.com/user-attachments/assets/cd6e3472-5dde-4194-bb27-d22b7e93fd16)
포이의 스킨정보에 '수영복 콘테스트 : 포이는 물이 싫어'에서 일러스트와 로비 애니메이션이 겹쳐서 나오는 버그가 있습니다. 일러스트는 다운이 되지만 애니메이션은 다운이 안되며, 이는 중파 옵션을 켰다 끄거나 사이트를 나갔다 들어와도 고쳐지지 않습니다.

**Comment by WolfgangKurz** [comment]
e1272a1c90d032b7eebc1a4ae248680239ff7e4f 에서 수정되었습니다
