### ISSUE TITLE
장비 페이지 등급 변경 불가

### ISSUE THREAD

**Issue by aaaaaaaaaaaaa9** [WolfgangKurz/LastOriginWiki#118]
![Screenshot_20240919_152649_Whale](https://github.com/user-attachments/assets/3454c1e3-5447-4a75-9195-355442959e2b)
장비 페이지에서 하위 등급을 선택해도 정보가 갱신되지 않아 하위 등급의 정보가 표시되지 않습니다.

**Comment by WolfgangKurz** [comment]
77f6f0d4d00b4d9d912afa64c23116fd06f36fd2 에서 수정되었습니다.
