### ISSUE TITLE
잘려진 일러스트레이션이 다운로드 되는 오류가 있습니다

### ISSUE THREAD

**Issue by LemonadeOmega** [WolfgangKurz/LastOriginWiki#126]
![3P_Aqua_0_O](https://github.com/user-attachments/assets/ba238b47-6f87-49a7-9141-5dd025e46942)
![3P_Aqua_0_O_BigSmile](https://github.com/user-attachments/assets/0fd2814a-8a94-40f9-b41f-44745482f59d)

기본 표정 일러스트레이션은 문제 없지만,
다른 표정 일러스트레이션은 두 번째와 같이 
잘려져 있는 상태의 일러스트레이션이 다운로드 됩니다.
두 일러스트레이션 모두 확장자 명 png로 다운로드 했습니다

**Comment by WolfgangKurz** [comment]
Fixed 9f8e2b54cfa26f98a529d398cce56d84dcdd4eda
