### ISSUE TITLE
Babariana skin live 2d motion issue

### ISSUE THREAD

**Issue by mixedc** [WolfgangKurz/LastOriginWiki#127]
![20241105_000927](https://github.com/user-attachments/assets/1fc3e7f5-3b46-433b-a0e2-7d59a3d6885d)
Babariana Dream-weaver skin Issue
When user touches babariana 3 times, she shows a special motion. But in wiki, her movement has a glitch like the screenshot.

**Comment by WolfgangKurz** [comment]
This is already known issue, but there's no way to fix at web as i know (as i find).
All versions of Official spine runtime libraries has same error, incorrect skin rendering.
(Unity version is fine)

**Comment by WolfgangKurz** [comment]
BTW, displaying static image at background is fixable bug, will be fixed next update.

**Comment by WolfgangKurz** [comment]
Additional: Found bug for animation processing. Above bug will be fixed with.

**Comment by WolfgangKurz** [comment]
has fixed at 0759cf85c0ab95ee93c723b0eae516c9bce273ab

**Comment by mixedc** [comment]
Appreciate it! Thanks to this convenient program, I can enjoy LO much
easier.

2024년 11월 6일 (수) 오전 4:32, Wolfgang Kurz ***@***.***>님이 작성:
