### ISSUE TITLE
Action algorithm for Predator_EW2

### ISSUE THREAD

**Issue by GHPSKSG** [WolfgangKurz/LastOriginWiki#53]
![Screenshot_20230630_191850_Samsung Internet](https://github.com/WolfgangKurz/LastOriginWiki/assets/138210986/c6e3b937-7dd1-4ea4-abe1-3cd67824af0b)

https://lo.swaytwig.com/enemies/Predator_EW2

**Comment by WolfgangKurz** [comment]
Will not be added when "07/04 game data update" related update.

**Comment by WolfgangKurz** [comment]
added on live.
