### ISSUE TITLE
신규스킨 출시 순서 정보 오류

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#56]
신규스킨 메인 및 나스호른 정보가 일부 순서 오류 및 누락되어있습니다
![스킨출신 순서 누락 및 오류](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/57ebfabe-f051-42e8-b563-6572dd973139)
![패치내역](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/75f9d969-5ed9-4c96-a9f4-4021e09d0bf8)

**Comment by WolfgangKurz** [comment]
released
