### ISSUE TITLE
사이트 접속 불량접수

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#59]
전투원 출시일 버튼을 누르면 해당 페이지로 넘어가지 못하고 어느 버튼을 누렸도 전혀 작동되지 못하고 있습니다. 혹시나 몰라 캐시 삭제와 크롬으로 옮겨서 실험을 했지만 동일한 문제가 계속 발생되고 있습니다.

**Comment by WolfgangKurz** [comment]
수정되었습니다.
