### ISSUE TITLE
테일러 클로스컷 1번 패시브 탐미주의 설명 텍스트 불일치

### ISSUE THREAD

**Issue by GHPSKSG** [WolfgangKurz/LastOriginWiki#61]
교본:
라운드 개시 시, 자신이 배치된 열에 따라 각기 다른 효과를 획득하며, 액티브 스킬의 추가 효과가 변경됩니다.

인게임:
라운드 개시 시, 자신이 배치된 열에 따라 각기 다른 효과를 획득하며, 액티브 스킬의 추가 효과가 변경됩니다.
적 개체 수가 1인 경우 <야전 마름질>사용 시, 위치와 관계 없이 해당 타입에 맞는 효과가 두 배로 증폭되어 추가 적용됩니다. (중첩 불가)

**Comment by WolfgangKurz** [comment]
테일러 클로스컷 및 올리비아 스타수어 변경 반영하여 배포되었습니다.
