### ISSUE TITLE
스킬목록에 해로운 효과 추가했으면 좋겠습니다

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#62]
전투원 정보창에 스킬 효과 필터목록에 해로운 효과가 추가되면 좋겠습니다.
그리고 가능하면 전투원 검색기능처럼  스킬도 검색할 수 있는 기능이 있으면 좋겠습니다

**Comment by WolfgangKurz** [comment]
고려하겠습니다.

**Comment by WolfgangKurz** [comment]
상세검색 기능 추가되어 반영되었습니다.
