### ISSUE TITLE
스킨출시 정보누락

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#68]
![화면 캡처 2023-10-31 213727](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/ddfc45dd-910d-463f-88af-5440718fc85b)

오니풍 무녀복 (드라큐리나), 물에 젖은 귀신 복장 (프로스트 서펀트) 누락

**Comment by WolfgangKurz** [comment]
수정되었습니다.
