### ISSUE TITLE
Some bugs I found

### ISSUE THREAD

**Issue by NexySlime** [WolfgangKurz/LastOriginWiki#70]
Source: https://lo.swaytwig.com/
Error: Uncaught (in promise) Error: No locale data has been registered for any of the locales: en, en

Source: Any stage in World
Error: Clicking any stage node will only bring out the story options of the stage, but not the stage info, need to refresh page for it to show up

**Comment by WolfgangKurz** [comment]
Now fixed

**Comment by WolfgangKurz** [comment]
second one now fixed
