### ISSUE TITLE
브륀힐드 스킬 버프보기 및 스토리 다시보기 텍스트 짤림현상

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#71]
![화면 캡처 2023-11-19 153855](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/341ecfe0-bc90-480b-b614-757c49d287c4)

패시브2 가까이 오지마의 일부 버프내용이 패시브1 스캴드메르로 옮겨졌어요

크롬을 이용해도 스토리를 뷰어로 보면 텍스트가 잘라져있습니다

**Comment by WolfgangKurz** [comment]
버프 내용은 개발사에서 적용 대상 및 범위를 별도로 적용하기 위해서 다른 스킬에 작성하는 경우가 있으며 데이터 오류가 아닙니다.

스토리 뷰어의 글자 문제는 인지하고 있으며, 아직 개발중인 기능이기에 즉시 수정되지 않습니다.

**Comment by WolfgangKurz** [comment]
스토리 플레이어의 글자 잘림 문제가 수정되었습니다.
문제가 여전한 경우 새로운 이슈로 등록해주시기 바랍니다.

또한, 이슈는 문제 하나당 하나의 이슈로 등록해주세요.
