### ISSUE TITLE
레모네이드 베타 스킬정보 보이지 않음

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#74]
![캡처_2023_12_01_09_45_46_595](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/0ee636b4-aa48-447b-9854-ba158e110a51)

**Comment by Mengsk1** [comment]
버프 보기도 수정부탁드립니다
-----Original Message-----

**Comment by WolfgangKurz** [comment]
버프 보기 관련하여 이름 없는 버프를 사용자가 인지하기 힘들 것으로 판단해 관련 내용을 개선하는 업데이트를 진행했습니다.
이후 추가 수정사항/버그가 있다면 새 이슈로 등록해주세요.
