### ISSUE TITLE
퀸오브메인 - 물 만난 사자 스킨 버그

### ISSUE THREAD

**Issue by tempUsergg** [WolfgangKurz/LastOriginWiki#75]
![image](https://github.com/WolfgangKurz/LastOriginWiki/assets/144774215/adf96b22-6d2a-4a33-8ca9-016e325aa09b)

https://lo.swaytwig.com/units/PECS_QueenMane

표정 이미지 좌표가 맞지 않는것으로 보임

**Comment by WolfgangKurz** [comment]
수정되었습니다.
