### ISSUE TITLE
더치걸 스킨 오류

### ISSUE THREAD

**Issue by inouter** [WolfgangKurz/LastOriginWiki#76]
더치걸의 행복한 작은 산타 스킨의 오류가 있는것 같습니다

구글버젼과 원스토어 버젼 중파 모두 동일한 일러스트가 나옵니다

중파가 아닌 일러스트도 스토어 종류에 관계없이 같은 일러스트가 나오는데 맞는건지 확인부탁합니다

**Comment by WolfgangKurz** [comment]
확인하는 한 동일해보입니다.
차이가 확실히 있다면 스크린샷으로 알려주시기 바랍니다.
