### ISSUE TITLE
엔라이 마법소녀 외전 스토리 추가 요청

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#77]
엔라이 마법소녀 외전 스토리 추가해주세요

**Comment by WolfgangKurz** [comment]
추가되어있습니다.
누락되었다면 서브스토리 목록 화면을 스크린샷해서 첨부하시거나 제목을 적어주세요.

**Comment by Mengsk1** [comment]
![엔라이 누락 스토리](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/c3952fec-65a8-4952-913a-43575c338943)

외전 이야기: 쿠노이치 엔라이 (누군가의 손길이 닿아) 외전 스토리 누락
![Screenshot 2023-12-28 at 09 36 08](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/a5a4aaa4-313a-452c-8271-ca67cafd158e)

스킨 출시일이 보이지 않으면 출시일을 클릭하면 다른 곳 버튼이 클릭되지 않고 있습니다
캐시 파일하고 모바일로 해봐도 안됩니다

**Comment by WolfgangKurz** [comment]
수정되었습니다.
