### ISSUE TITLE
Is it possible to show the simple pic of the SD characters besides the unit's illustrations?

### ISSUE THREAD

**Issue by Semper-Augustus** [WolfgangKurz/LastOriginWiki#79]
Greetings, I can find the icon of a SD character in the Skin Info, so I wonder if it is possible to show a pic of it without the motions. (I know it might be too troublesome to add all the motions, lol)

**Comment by WolfgangKurz** [comment]
There's no plans to offer any SD information.

**Comment by Semper-Augustus** [comment]
I understand, thank you for your reply and have a nice day.
