### ISSUE TITLE
세계정보- 지도로 들어가면 이미지가 안보입니다

### ISSUE THREAD

**Issue by touhouflandre495** [WolfgangKurz/LastOriginWiki#82]
![스크린샷 2024-01-25 100708](https://github.com/WolfgangKurz/LastOriginWiki/assets/156405026/a3caca20-ad59-458f-be06-f6c17c023006)

이번 우주황금 이벤트는 멀쩡한데, 메인스토리나 상시이벤트 지역에서 이렇게 하얀색으로만 뜨네요

**Comment by WolfgangKurz** [comment]
수정되었습니다.
