### ISSUE TITLE
스토리 뷰의 베로니카 일러스트 오류

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#85]
![누군가 바랐던 소원1부 ev1-1ed 베로니카 사진](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/f12ced9d-6788-4954-886f-36954cdbebb3)

스샷처럼 베로니카 일러스트의 얼굴부분이 따로 나오는 오류가 있는데 다른 스토리의 베로니카도 동일한 오류가 나왔습니다

**Comment by WolfgangKurz** [comment]
수정되었습니다.
