### ISSUE TITLE
획득처 상세설명에 싹다 메인스토리로 보입니다

### ISSUE THREAD

**Issue by touhouflandre495** [WolfgangKurz/LastOriginWiki#87]
![스크린샷 2024-02-15 213328](https://github.com/WolfgangKurz/LastOriginWiki/assets/156405026/c8dfa402-d4a4-4abf-bb4b-8c0ab2230108)
이렇게 보이네요

**Comment by WolfgangKurz** [comment]
사용중인 OS 및 브라우저를 알려주세요

**Comment by touhouflandre495** [comment]
> 사용중인 OS 및 브라우저를 알려주세요

윈도우 11 마이크로소프트 엣지입니다
