### ISSUE TITLE
스토리 뷰 장화, 바르그 일러스트 표시안됨

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#88]
![장화](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/d2bb1ef1-bb20-4970-bbd0-f8e57626ae40)
![바르그](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/59adecba-1ecc-44fc-91b2-6796c01011dc)

모든 스토리에서 장화, 바르그 일러스트가 나오지 않고 있습니다

**Comment by WolfgangKurz** [comment]
수정되었습니다.
