### ISSUE TITLE
MISS ORCA 3rd season 가사맞춤 표시오류

### ISSUE THREAD

**Issue by Mengsk1** [WolfgangKurz/LastOriginWiki#90]
![가사](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/c4c04f12-9ccf-4452-96bc-518ccb9ece28)

![Screenshot 2024-02-18 at 22 52 17](https://github.com/WolfgangKurz/LastOriginWiki/assets/140134177/be01047b-f351-4580-9beb-fe2f9371bcb0)
다른 노래곡들은 2번째 사진처럼 노래에 맞춰 해당 가사가 표시가 나와야하는데 미스 오르카 3rd에서는 어느 곡도 표시에 나오지 않고 있습니다

**Comment by WolfgangKurz** [comment]
해당 곡들은 가사의 시간 정보를 입력하지 않았습니다.
별도로 기여되지 않는 이상, 제가 직접 추가할 예정은 없습니다.

**Comment by Mengsk1** [comment]
그럼 오류가 아닌군요 알겠습니다

**Comment by WolfgangKurz** [comment]
https://github.com/WolfgangKurz/LastOriginWiki/blob/master/src/libs/BGM.ts
위 소스코드 참조해주시기 바랍니다.
감사합니다.
