### ISSUE TITLE
워울프 2패시브 텍스트 오류

### ISSUE THREAD

**Issue by aaaaaaaaaaaaa9** [WolfgangKurz/LastOriginWiki#96]
![Screenshot_20240305_124348_Whale](https://github.com/WolfgangKurz/LastOriginWiki/assets/162282098/377a8b10-0e57-41e1-bcc5-e9b2ed63d409)
![Screenshot_20240305_154752](https://github.com/WolfgangKurz/LastOriginWiki/assets/162282098/93390e87-75f3-4d73-9d29-6fb84a28ab84)

워울프의 2패시브 텍스트가 밸런스 조정 전의 내용으로 나오며 하단의 버프량 또한 잘못되어 있습니다.

**Comment by WolfgangKurz** [comment]
Fixed and updated to live
